#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd -- "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP_ROOT="$(mktemp -d)"
DIR1="$TMP_ROOT/case1"
DIR2="$TMP_ROOT/case2"
mkdir -p "$DIR1" "$DIR2"
printf 'x' >"$DIR1/Movie (2007).mkv"
printf 'x' >"$DIR1/Movie (2007).eng.srt"
printf 'x' >"$DIR1/Movie 2 (2019).eng.srt"
printf 'x' >"$DIR1/Movie (2007) eng.vtt"
printf 'x' >"$DIR2/Film.mkv"
printf 'x' >"$DIR2/Film.eng.srt"
printf 'x' >"$DIR2/Film.eng.sdh.srt"
printf 'x' >"$DIR2/Film.ita.forced.vtt"
printf 'x' >"$DIR2/Film.eng.commentary.ass"
source "$ROOT/scripts/lib/media_filters.sh"
out1="$(discover_external_subs "$DIR1/Movie (2007).mkv")"
echo "$out1" | grep -q "$DIR1/Movie (2007).eng.srt|eng|0|0|0|srt"
! echo "$out1" | grep -q "$DIR1/Movie 2 (2019).eng.srt"
echo "$out1" | grep -q "$DIR1/Movie (2007) eng.vtt|eng|0|0|0|vtt"
unset PREFER_SDH
out2="$(discover_external_subs "$DIR2/Film.mkv")"
echo "$out2" | grep -q "$DIR2/Film.eng.srt|eng|0|0|0|srt"
! echo "$out2" | grep -q "$DIR2/Film.eng.sdh.srt"
echo "$out2" | grep -q "$DIR2/Film.ita.forced.vtt|ita|1|0|0|vtt"
! echo "$out2" | grep -q "$DIR2/Film.eng.commentary.ass"
PREFER_SDH=1
out3="$(discover_external_subs "$DIR2/Film.mkv")"
echo "$out3" | grep -q "$DIR2/Film.eng.sdh.srt|eng|0|1|0|srt"
! echo "$out3" | grep -q "$DIR2/Film.eng.srt|eng|0|0|0|srt"
