#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

printf '==> Codex setup in %s\n' "$REPO_ROOT"

need_cmd() {
  command -v "$1" >/dev/null 2>&1
}

install_ffmpeg_if_missing() {
  if need_cmd ffmpeg && need_cmd ffprobe; then
    echo "ffmpeg/ffprobe already available"
    return 0
  fi

  if [[ "${CODEX_SKIP_SYSTEM_DEPS:-0}" = "1" ]]; then
    echo "WARN: CODEX_SKIP_SYSTEM_DEPS=1 set; skipping ffmpeg install"
    return 1
  fi

  echo "ffmpeg/ffprobe missing; attempting install"

  if need_cmd apt-get; then
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -y && apt-get install -y ffmpeg
  elif need_cmd dnf; then
    dnf install -y ffmpeg ffmpeg-libs
  elif need_cmd yum; then
    yum install -y epel-release || true
    yum install -y ffmpeg
  elif need_cmd brew; then
    brew install ffmpeg
  else
    echo "WARN: no supported package manager found to install ffmpeg"
    return 1
  fi

  if need_cmd ffmpeg && need_cmd ffprobe; then
    return 0
  fi

  echo "WARN: ffmpeg install attempt finished but ffmpeg/ffprobe are still missing"
  return 1
}

mkdir -p .codex/checkpoints
cat > .codex/env.sh <<ENV
# shellcheck shell=bash
# Generated by scripts/codex/setup.sh
export JELLYFIN_CONVERTER_ROOT="$REPO_ROOT"
ENV

chmod +x run.sh scripts/jellyfin_converter.sh tests/run.sh scripts/codex/setup.sh scripts/codex/maintenance.sh scripts/codex/check-workflow-conformance.sh scripts/check-fast.sh scripts/check-full.sh scripts/check-changed.sh 2>/dev/null || true

have_media_tools=0
if install_ffmpeg_if_missing; then
  have_media_tools=1
fi

echo "==> Tool versions"
printf 'bash: %s\n' "$(bash --version | head -n1)"
if need_cmd ffmpeg; then
  printf 'ffmpeg: %s\n' "$(ffmpeg -version | head -n1)"
else
  echo "ffmpeg: missing"
fi
if need_cmd ffprobe; then
  printf 'ffprobe: %s\n' "$(ffprobe -version | head -n1)"
else
  echo "ffprobe: missing"
fi

echo "==> Running smoke validation"
echo "bash scripts/codex/check-workflow-conformance.sh"
bash scripts/codex/check-workflow-conformance.sh

echo "bash scripts/check-fast.sh"
if [[ "$have_media_tools" -eq 1 ]]; then
  bash scripts/check-fast.sh
else
  echo "Running reduced smoke validation without ffmpeg/ffprobe"
  echo "bash -n scripts/jellyfin_converter.sh"
  bash -n scripts/jellyfin_converter.sh
  echo "./tests/run.sh tests/suite_parser.sh"
  ./tests/run.sh tests/suite_parser.sh
fi

echo "Setup completed"
